### PR TITLE
[release-1.5] Backport bugfixes to release-1.5 branch

### PR DESCRIPTION
**Pull request by ericphanson**
Looking at the commits on master that are not on release-1.5, they all appear to be bugfixes. So I did

```bash
❯ git merge-base master release-1.5                                                                 
5d00bddf2db81b0ea62990b4d81fe5bf51c38b10

❯ git cherry-pick -x 5d00bddf2db81b0ea62990b4d81fe5bf51c38b10..c445f456aeb8e481620102ce40a6be618a8dcc3f

```
where I got the latter commit from
```bash
❯ git log # on `master`
commit 43899e71eed709866f96dd624f1c369a1c8e26a3 (HEAD -> master, tag: v1.6.0, origin/master, origin/HEAD)
Author: Stefan Karpinski <stefan@karpinski.org>
Date:   Wed Dec 15 09:41:37 2021 -0500

    bump version to v1.6.0

commit c445f456aeb8e481620102ce40a6be618a8dcc3f
Merge: ab628ab 4e0408a
Author: Stefan Karpinski <stefan@karpinski.org>
Date:   Tue Dec 14 22:11:28 2021 -0500

    Merge pull request #170 from JuliaLang/tan/chunkedtransfer
    
    debug callbacks and end-to-end tests for #167
```
and then a bunch of `git cherry-pick --skip`s and got here, and then added a commit bumping the version.

### CODE REVIEW

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
@StefanKarpinski Does this sound good to you? If so, I'll merge the PR, register a new release, and bump the stdlib version on Julia 1.7.

**Comment by DilumAluthge** [comment]
@ericphanson Any chance you could regenerate this PR, but with `git cherry-pick -x`? I find that this makes it a lot easier to map the cherry-picks back to the original commits?

**Comment by ericphanson** [comment]
> @ericphanson Any chance you could regenerate this PR, but with `git cherry-pick -x`?

Ok, done

**Comment by ericphanson** [comment]
bump

**Comment by ericphanson** [comment]
bump

**Comment by ericphanson** [comment]
Thank you @DilumAluthge ! What’s the next step to get this into Julia 1.7.X?

**Comment by DilumAluthge** [comment]
1. In the `JuliaLang/Downloads.jl` repository, go to the `release-1.5` branch, and make a note of the latest commit on that branch. Let's call that value `NEWCOMMIT`.
2. Clone the `JuliaLang/julia` repository, and `cd` into it.
3. Check out the `release-1.7` branch.
4. Delete all directories matching `deps/checksums/Downloads-*`
5. Open the `stdlib/Downloads.version` file. In that file:
    - Make sure that the `DOWNLOADS_BRANCH = ...` line says `DOWNLOADS_BRANCH = release-1.7`. If that's not what it says, change that line so it reads `DOWNLOADS_BRANCH = release-1.7`.
    - Look at the line that says `DOWNLOADS_SHA1 = ...`. Make a note of that value. Let's call that value `OLDCOMMIT`.
    - Change the line that says `DOWNLOADS_SHA1 = ...` so that it now says line that says `DOWNLOADS_SHA1 = NEWCOMMIT`
6. Run `make -C stdlib`. This will generate the new checksums.
7. `git add -A` and `git commit`.
8. `git push`, and open a new pull request, cc Stefan and me in the PR.

**Pull request merged**
