### PR TITLE
only create one watcher task

### PR DESCRIPTION
**Pull request by vtjnash**
Expected to just be an optimization

(See this diff without whitespace: https://github.com/JuliaLang/Downloads.jl/pull/160/files?diff=unified&w=1)

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Can you explain the reasoning for why this is correct?

**Comment by vtjnash** [comment]
Ah, true, I guess it generally is not, since the event flags may be wrong.

**Comment by StefanKarpinski** [comment]
And wouldn't the file descriptor potentially be wrong too? It seems unlikely for curl to change sockets for the same download, but it seems like it could potentially happen.

**Comment by vtjnash** [comment]
Yeah, I'll fix this in FileWatching instead

**Pull request closed without merging**
