### PR TITLE
Add `maxlog=1_000` to some `@error` messages

### LINKED ISSUE #189: Add `maxlog` to `@error` messages?
I just had a CI run take 1hr 20 minutes instead of 30, and the logs didn't show. I got GHA to let me download them, and found a 4 GB file with
```julia
┌ Error: curl_multi_socket_action: 8
└ @ Downloads.Curl /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/Downloads/src/Curl/utils.jl:36
```
repeated 14 million times. This was disappointing to me because the PR the CI failed on was adding a lock around some data loading to avoid the Downloads multithreading bugs on 1.7, but also that's an incredible number of error messages.

What about adding `maxlog=10_000` or something? If it's really high, then it probably won't be ever dropping useful messages, and it can avoid this pathological scenario. And of course one can just use a logger that doesn't respect `maxlog` to get them, if needed.

### PR DESCRIPTION
**Pull request by DilumAluthge**
Fixes #189

### CODE REVIEW

**Comment by DilumAluthge** [comment]
cc: @ericphanson

**Review by ericphanson — APPROVED** [review]
This definitely hits the one I was running into, though maybe we might as well do all of them? https://cs.github.com/JuliaLang/Downloads.jl?q=%40error

**Comment by DilumAluthge** [comment]
Sure, let's do all of them. Want to make a PR? You can make your PR target my `dpa/error-maxlog` branch.

**Review by StefanKarpinski — APPROVED** [review]

**Comment by KristofferC** [comment]
10'000 sounds a bit excessive as well. When you have read 9999, do you want to see another one?

**Comment by StefanKarpinski** [comment]
Agree, 1000 seems like plenty.

**Comment by DilumAluthge** [comment]
The Linux x86 nightly failures are https://github.com/JuliaLang/julia/issues/45045

**Pull request merged**
