### PR TITLE
Multi: add grace period before calling done! (default: 30s)

### PR DESCRIPTION
**Pull request by StefanKarpinski**
This uses the Multi object's already-allocated timer to set a timer when the number of in-progress downloads reaches zero, to clean up the curl multi-handle and associated resources when the timer goes off. If another download is started before then, then the timer is started again once the number of downloads reaches zero again. If a Multi object is garbage collected before its cleaup timer fires, it will be finalized earlier, so the cleanup occurs at the earlier of the two. If the grace period is zero, then `done!` is called immediately when the number of concurrent downloads reaches zero. If the grace period is larger than `typemax(UInt64) ÷ 1000` then no timer is set and the cleanup only occurs when the Multi object is garbage collected.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
@KristofferC & @aviks: feel free to look at the technical parts of this PR, but what I'm really interested in is feedback on the general concept of having a grace period before cleaning up a downloader's resources. We could make the default downloader behave the way it did before by making its grace period zero, but this seems like a pretty decent default since it's fairly common for people to write code that does more than one batch of downloads to the same server and this makes that noticeably faster since it can reuse already-open connections. It's still possible to use a locally scoped `Downloader` object to delimit the duration of libcurl resources since if a downloader is garbage collected before its grace period expires, the resources are finalized immediately. If, on the other hand, someone naively keeps a global reference to a `Downloader` object—in the future we might allow meaningful configuration of them that someone wants to apply—then this will still reclaim resources after some time.

**Comment by StefanKarpinski** [comment]
Might also make sense to make the default grace period shorter: 60 seconds is an eternity in computer time. Apache's default Keep-Alive timeout is 15 seconds; not directly related, but it feels like the same kind of thing.

**Comment by StefanKarpinski** [comment]
Update: changed the default grace period to 30 seconds.

**Comment by StefanKarpinski** [comment]
I'm going ahead with this since the old behavior is just a special case of this one. If we decide we don't want the grace period by default, we can always make the default be a grace period of zero and retain this functionality for those who do want it.

**Comment by KristofferC** [comment]
Maybe 30 sec is still kinda long but I don't really know. 🤷‍♂️

**Comment by StefanKarpinski** [comment]
Yeah, who knows?! I figure that in most circumstances keeping some resources around on a client doesn't matter. On a server, you're likely to be serving lots of clients, but on the client that's not an issue.

**Pull request merged**
