### PR TITLE
support parsing FTP response "headers" (ignore them)

### LINKED ISSUE #36: Downloading files with FTP protocol fails with `Could not resolve host`
Julia v1.5:
```
julia> download("ftp://xmlsoft.org/libxslt/libxslt-1.1.33.tar.gz")
"/tmp/jl_PhxwJQ"
```

with `Downloads`:
```
julia> Downloads.download("ftp://xmlsoft.org/libxslt/libxslt-1.1.33.tar.gz")
ERROR: Could not resolve host: 
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] (::Downloads.var"#2#3"{Vector{Pair{String, String}}, Downloads.Downloader, String})(io::IOStream)
   @ Downloads ~/repo/julia/usr/share/julia/stdlib/v1.6/Downloads/src/Downloads.jl:69
 [3] arg_write(f::Downloads.var"#2#3"{Vector{Pair{String, String}}, Downloads.Downloader, String}, arg::Nothing)
   @ ArgTools ~/repo/julia/usr/share/julia/stdlib/v1.6/ArgTools/src/ArgTools.jl:101
 [4] #download#1
   @ ~/repo/julia/usr/share/julia/stdlib/v1.6/Downloads/src/Downloads.jl:49 [inlined]
 [5] download
   @ ~/repo/julia/usr/share/julia/stdlib/v1.6/Downloads/src/Downloads.jl:48 [inlined]
 [6] top-level scope
   @ REPL[8]:1
```

### PR DESCRIPTION
**Pull request by StefanKarpinski**
@giordano, when I test locally with Julia 1.5, this fixes #36, but I also wasn't seeing the error that you were. Can you try this and verify that it seems to work for you? I should probably add a test, but I'm not sure I want the tests to rely on some random ftp server being up and working.

### CODE REVIEW

**Comment by giordano** [comment]
Sorry, I didn't mention it explicitly (although it can be seen in the stacktrace) but I was using `Downloads.download` in Julia v1.6.

With this branch download doesn't fail but I get empty files

**Comment by StefanKarpinski** [comment]
In order to try this out on master, you have to recompile it with this as the newest copy of the stdlib. Is that what you did or did you try something else? The ways to try this out (in increasing order of annoyance) are:

1. Use Julia 1.3-1.5 and load it as a normal package
2. Use Julia master and change the uuid here before loading it
3. Use Julia master and recompile with this version of Downloads.

I've tried all three and I can successfully download the ftp URL in the issue.

**Comment by giordano** [comment]
No, I followed https://github.com/JuliaLang/Pkg.jl/blob/master/README.md#using-the-development-version-of-pkgjl, but I get the same on julia v1.5 by installing the package and on master with the trick above. I can try again as soon as I get back to my computer

**Comment by giordano** [comment]
Julia v1.5:
```julia
julia> file = download("ftp://xmlsoft.org/libxslt/libxslt-1.1.33.tar.gz")
"/tmp/jl_X5CUDq"

shell> file $file
/tmp/jl_X5CUDq: gzip compressed data, last modified: Thu Jan  3 18:29:57 2019, max compression, from Unix, original size modulo 2^32 21729280

julia> using Downloads
[ Info: Precompiling Downloads [f43a241f-c20a-4ad4-852c-f6b1247861c6]
WARNING: using Downloads.download in module Main conflicts with an existing identifier.

julia> file = Downloads.download("ftp://xmlsoft.org/libxslt/libxslt-1.1.33.tar.gz")
"/tmp/jl_qtmDkp"

shell> file $file
/tmp/jl_qtmDkp: empty
```

Julia master, by using the local `Downloads` environment:
```
julia> using Downloads
[ Info: Precompiling Downloads [d43a241f-c20a-4ad4-852c-f6b1247861c6]

julia> file = Downloads.download("ftp://xmlsoft.org/libxslt/libxslt-1.1.33.tar.gz")
"/tmp/jl_Gmv79r"

shell> file $file
/tmp/jl_Gmv79r: empty
```

**Comment by StefanKarpinski** [comment]
That's bizarre. I guess I can put a temporary test that downloading this file works and try all the platforms.

**Comment by StefanKarpinski** [comment]
Well, that's a smörgåsbord of failures. It seems like the FTP server has blacklisted Travis IP addresses for the FreeBSD and Windows machines. The Linux servers display the behavior you're seeing. Presumably you're running Linux, @giordano? My first guess would be that the FTP support in binary builds for libcurl are messed up on Linux.

**Comment by giordano** [comment]
> The Linux servers display the behavior you're seeing. Presumably you're running Linux, @giordano?

Yep

> My first guess would be that the FTP support in binary builds for libcurl are messed up on Linux.

:persevere:

**Comment by giordano** [comment]
Using the `curl` in `LibCURL_jll` with Julia v1.5 I can download the file via FTP:
```julia
julia> using LibCURL_jll

julia> curl(x -> run(`$x -o libxslt-1.1.33.tar.gz 'ftp://xmlsoft.org/libxslt/libxslt-1.1.33.tar.gz'`))
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3363k  100 3363k    0     0  1817k      0  0:00:01  0:00:01 --:--:-- 1817k
Process(`/home/mose/.julia/artifacts/2f1155c51d79440c61a695481f3cfb3e9b4e3f04/bin/curl -o libxslt-1.1.33.tar.gz ftp://xmlsoft.org/libxslt/libxslt-1.1.33.tar.gz`, ProcessExited(0))

shell> file libxslt-1.1.33.tar.gz
libxslt-1.1.33.tar.gz: gzip compressed data, last modified: Thu Jan  3 18:29:57 2019, max compression, from Unix, original size modulo 2^32 21729280
```

**Comment by StefanKarpinski** [comment]
I can reproduce the same behavior on Linux. Here's the verbose output on macOS (works):
```jl
julia> download("ftp://xmlsoft.org/libxslt/libxslt-1.1.33.tar.gz", verbose=true);
* Found bundle for host xmlsoft.org: 0x7fb23dfbbe50 [serially]
* Re-using existing connection! (#0) with host xmlsoft.org
* Connected to xmlsoft.org (91.121.203.120) port 21 (#0)
* Request has same path as previous transfer
> EPSV
* Connect data stream passively
* ftp_perform ends with SECONDARY: 0
< 229 Entering Extended Passive Mode (|||38172|).
*   Trying 91.121.203.120:38172...
* Connecting to 91.121.203.120 (91.121.203.120) port 38172
* Connected to xmlsoft.org (91.121.203.120) port 21 (#0)
> SIZE libxslt-1.1.33.tar.gz
< 213 3444093
> RETR libxslt-1.1.33.tar.gz
< 150 Opening BINARY mode data connection for libxslt-1.1.33.tar.gz (3444093 bytes).
* Maxdownload = -1
* Getting file with size: 3444093
* Remembering we are in dir "libxslt/"
< 226 Transfer complete.
* Connection #0 to host xmlsoft.org left intact
```
Here's the verbose output on Linux (fails):
```jl
julia> download("ftp://xmlsoft.org/libxslt/libxslt-1.1.33.tar.gz", verbose=true);
*   Trying 91.121.203.120:21...
* Connected to xmlsoft.org () port 21 (#0)
< 220 (vsFTPd 2.2.2)
> USER anonymous
< 331 Please specify the password.
> PASS ftp@example.com
< 230 Login successful.
> PWD
< 257 "/"
* Entry path is '/'
> CWD libxslt
* ftp_perform ends with SECONDARY: 0
< 250 Directory successfully changed.
> EPSV
* Connect data stream passively
< 229 Entering Extended Passive Mode (|||26410|).
* Could not resolve host:
* Can't resolve new host :26410
* Closing connection 0
```
I have no idea why this would be different on Linux than macOS or what the `curl` command would be doing differently here than the default `libcurl` behavior.

**Comment by StefanKarpinski** [comment]
Here's the verbose output of the `curl` command on Linux for comparison:
```
* Connected to xmlsoft.org (91.121.203.120) port 21 (#0)
< 220 (vsFTPd 2.2.2)
> USER anonymous
< 331 Please specify the password.
> PASS ftp@example.com
< 230 Login successful.
> PWD
< 257 "/"
* Entry path is '/'
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0> CWD libxslt
* ftp_perform ends with SECONDARY: 0
< 250 Directory successfully changed.
> EPSV
* Connect data stream passively
< 229 Entering Extended Passive Mode (|||31781|).
*   Trying 91.121.203.120:31781...
* Connecting to 91.121.203.120 (91.121.203.120) port 31781
* Connected to xmlsoft.org (91.121.203.120) port 21 (#0)
> TYPE I
< 200 Switching to Binary mode.
> SIZE libxslt-1.1.33.tar.gz
< 213 3444093
> RETR libxslt-1.1.33.tar.gz
< 150 Opening BINARY mode data connection for libxslt-1.1.33.tar.gz (3444093 bytes).
* Maxdownload = -1
* Getting file with size: 3444093
{ [2896 bytes data]
 27 3363k   27  917k    0     0   673k      0  0:00:04  0:00:01  0:00:03  673k* Remembering we are in dir "libxslt/"
< 226 Transfer complete.
100 3363k  100 3363k    0     0  1921k      0  0:00:01  0:00:01 --:--:-- 1920k
* Connection #0 to host xmlsoft.org left intact
```
Trying to track down what the configuration difference might be.

**Comment by StefanKarpinski** [comment]
I'm going to merge the part of this that supports parsing FTP "headers" since that part is correct and at least allows doing FTP downloads on platforms where libcurl can do it. I'll make another PR with the tests and we can continue discussing why this particular FTP download doesn't work on Linux in that separate issue.

**Pull request merged**
