### PR TITLE
Stop the grace timer iff adding first handle (fix #99)

### LINKED ISSUE #99: Another download hang
The following consistently hangs during the second download at around 35% (progress callback just there for visualizing the hang):

```julia
import Downloads

function download(url)
    println("Downloading $url")
    Downloads.download(url; progress=(total,now)->print("$(round(100*now/total, digits=1))% ($(Base.format_bytes(now))/$(Base.format_bytes(total)))          \r"))
    println()
end

download("https://julia-bb-buildcache.s3.amazonaws.com/832f0d52e696354cdd22425aa70db1f209d62c9d84626a7e48cf4ca0190cfd50/8ae9d6affc9d3c0045f6d90f7c972db11b17d2babf4cfb3a204af49dd5afcaee/x86_64-linux-gnu.tar.gz")
download("https://julia-bb-buildcache.s3.amazonaws.com/832f0d52e696354cdd22425aa70db1f209d62c9d84626a7e48cf4ca0190cfd50/8ae9d6affc9d3c0045f6d90f7c972db11b17d2babf4cfb3a204af49dd5afcaee/powerpc64le-linux-gnu.tar.gz")
```

It does not happen when only downloading a single file, and does not require concurrent downloads like https://github.com/JuliaLang/Downloads.jl/issues/95. Tested on the latest backports-1.6, so it includes https://github.com/JuliaLang/Downloads.jl/pull/96.

### PR DESCRIPTION
**Pull request by StefanKarpinski**

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Alternative to https://github.com/JuliaLang/Downloads.jl/pull/101. Thanks for the diagnosis, @maleadt — I think this fix is clearer and makes the start and stop logic for the grace timer more symmetrical and thus, imo, less confusing. The issue with stopping the timer whenever `multi.handle` is not NULL is that there may be a timer going that was set by another ongoing download and stopping that will cause different kinds of hangs. I believe this stops the timer if and only if there could be a grace timer going or when the multi handle has never been used, which is harmless since stopping a libuv timer that hasn't been started is a no-op (we could avoid doing that by _also_ checking that `multi.handle != C_NULL` before stopping the timer).

**Comment by giordano** [comment]
Just to make sure the test is reliable on GitHub Actions, I [added Tim's test on top of `master`](https://github.com/giordano/Downloads.jl/commit/37f7b57d08323b4e1f27615e8b57f60118239582), without any of the fixes here or in #101, and with a timeout of 15 minutes, result: https://github.com/giordano/Downloads.jl/runs/1983343797.  Interestingly enough, the only platform passing the tests without timing out is... 64-bit Windows.

**Comment by DilumAluthge** [comment]
Does this PR close #99 and #101?

**Comment by fredrikekre** [comment]
I can't repro #95 with this patch (with HTTP/2 turned on). Likely also fixes https://github.com/JuliaLang/Downloads.jl/issues/94 but that one I have only been able to trigger in a running server and happens maybe once a day or something.

**Pull request merged**
